spring:

  # profile
  profiles:
    active: dev,default # java -jar app.jar --spring.profiles.active=dev
  application:
    name: ispong-oxygen
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # 请求管理
  servlet:
    multipart:
      max-file-size: 3MB # 上传最大文件大小
      max-request-size: 3MB # 上传最大请求体大小

  # spring-mail
  mail:
    host: smtp.qq.com # 邮箱服务器地址
    port: 465 # 邮箱服务器端口号
    username: ENC@[4FmaVNBbiNyVZEF2cDBwGml4ufMnYB6wEMHrBTDPg8MdYWUPlgV0uRyqwfttlaIOA6jl8DpSABXJO7QBVBbkWQ==] # 邮箱账号
    password: ENC@[bc4ClJDP6nX+XWTtZkBbXPCBlOvTqaWIVogQebWagYJCAO1WBZE2qkTstMp859nCrumGTxboQpNhywo75hPIFQ==] # 邮箱密码
    default-encoding: UTF-8 # 邮件字符集
    protocol: smtp # 邮件发送协议
    test-connection: false # 是否进行连接测试
    properties:
      mail.smtp.ssl.enable: true # 启动ssl协议访问
      mail.smtp.connectiontimeout: 10000 # 设置连接超时
      mail.smtp.timeout: 10000 # 设置超时
      mail.smtp.writetimeout: 10000 # 设置写入超时

  # spring-dataSource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/h2
    username: root
    password: root
  #    schema: classpath:db/schema.sql
  #    initialization-mode: embedded
  #    data: db/data.sql

  # h2-config
  # http://localhost:8888/spring-oxygen/h2-console
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

  # spring-security
  security:
    user:
      name: admin
      password: admin
      roles: OXYGEN_ADMIN

  # spring-quartz
  quartz:
    scheduler-name: quartzScheduler # 定时器名称
    auto-startup: true # 初始化后是否自动启动
    job-store-type: jdbc # job存储方式
    jdbc:
      schema: classpath:db/quartz_h2.sql # sql执行脚本
      comment-prefix: '#, --' # sql语句中的注释
      initialize-schema: embedded # 初始化数据库方式 embedded(不会重复初始化) always(每次都会初始化)
    startup-delay: 0s # 启动延迟时间
    overwrite-existing-jobs: false # 是否覆盖已存在job
    wait-for-jobs-to-complete-on-shutdown: false # 是否在关闭时等待job执行完毕
    properties:
      org:
        quartz:
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 20
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: false

# 服务器配置
server:
  servlet:
    context-path: /spring-oxygen # context
  port: 8888

# spring-logging
logging:
  level:
    root: info
    com.isxcode.oxygen.wechatgo: debug
    com.ispong.oxygen.flysql: debug
    com.ispong.oxygen.freecode: debug
  file:
    name: ./logs/spring.log
    max-size: 10MB
    max-history: 30
    total-size-cap: 100MB
    clean-history-on-start: true
  exception-conversion-word: '%wEx'
  pattern:
    level: '%5p'
    dateformat: 'yyyy-MM-dd HH:mm:ss.SSS'
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN}}){faint} %clr(${LOG_LEVEL_PATTERN}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD}'
    file: '%d{${LOG_DATEFORMAT_PATTERN}} ${LOG_LEVEL_PATTERN} %-5(${PID:- }) --- [%15.15t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD}}'
    rolling-file-name: '${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz'

# spring-oxygen
oxygen:
  freecode:
    module-path: com.ispong.oxygen.scheduler # 模块包的位置
    author: ispong # 作者
    version: 0.0.1 # 版本号
    base-entity-class: com.ispong.oxygen.flysql.common.BaseEntity # Entity基础类
    base-controller-class: com.ispong.oxygen.flysql.common.BaseController # Controller基础类
    ignore-columns: # 忽略字段
      - uuid
      - version
      - created_date
      - created_by
      - last_modified_date
      - last_modified_by
    file-types: # 需要生成哪些文件
      - controller
      - entity
      - service
      - repository

  wechatgo:
    app-id: wx5ada926e5489824f # appId
    app-secret: d49e9eaac5633e661ff207353a9c86b1 # appSecret
    token: test # custom server token
  flysql:
    datasource:
      pluto: # 第二数据源
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql.definesys.com:30002/pluto_dev
        username: pluto
        password: welcome1
  system:
    file:
      location: D://
    quartz:
      datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:~/h2
        username: root
        password: root

# jasypt
jasypt:
  encryptor:
    property:
      prefix: "ENC@[" # 标识前缀
      suffix: "]" # 标识后缀
    bean: customJasyptStringEncryptor # 使用自定义加密规则

# spring-actuator
management:
  endpoints:
    web:
      exposure:
        include: logfile,health,beans,metrics
  endpoint:
    logfile:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true


