server:
  port: 8080 # 端口号
  servlet:
    context-path: /isxcode # 上下文

spring:
  profiles:
    active: dev # 使用配置文件
  application:
    name: isxcode
  redis:
    host: 47.105.33.160
    port: 8088
    password: isxcode
  security:
    user:
      name: isxcode
      password: admin

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启sql语句日志打印

# 日志访问地址 http://localhost:8080/isxcode/actuator/logfile
# 默认开启访问路径 /actuator/health actuator/info
logging:
  config: classpath:logback-spring.xml
  path: logs
  file: logs/spring.log

# 配置actuator属性
management:
  endpoints:
    web:
      exposure:
        include: logfile,health,info
  endpoint:
    logfile:
      enabled: true # logfile
