# 基础配置

# java -jar app.jar --spring.profiles.active=dev
spring:
  profiles:
    active: dev # 默认全部使用开发环境的配置,如果需要其他的配置就通过命令的方式注入
  application:
    name: isxcode # 项目的名称
#  jackson:
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss

  # spring-mail 配置
  mail:
    host: smtp.qq.com # 邮箱服务器地址
    port: 465 # 邮箱服务器端口号
    username: ENC@[4FmaVNBbiNyVZEF2cDBwGml4ufMnYB6wEMHrBTDPg8MdYWUPlgV0uRyqwfttlaIOA6jl8DpSABXJO7QBVBbkWQ==] # 邮箱账号
    password: ENC@[bc4ClJDP6nX+XWTtZkBbXPCBlOvTqaWIVogQebWagYJCAO1WBZE2qkTstMp859nCrumGTxboQpNhywo75hPIFQ==] # 邮箱密码
    default-encoding: UTF-8 # 邮件字符集
    protocol: smtp # 邮件发送协议
    test-connection: false # 是否进行连接测试
    properties:
      mail.smtp.ssl.enable: true # 启动ssl协议访问
      mail.smtp.connectiontimeout: 10000 # 设置连接超时
      mail.smtp.timeout: 10000 # 设置超时
      mail.smtp.writetimeout: 10000 # 设置写入超时

# freemarker 设置
  freemarker:
    enabled: false # 使用启动springMvc
    cache: false # 关闭缓存
    charset: UTF-8 # 设置字符集
    template-loader-path: /templates/ # 设置模板地址
    check-template-location: false # 检查模板地址是否存在
#    settings: # freemarker官方配置

  # thymeleaf
#  thymeleaf:
#    prefix: classpath:/auth/
#  security:
#    oauth2:
#      client:
#        registration:
#          isxcode:
#            client-id: isxcode-client-id
#            client-secret: isxcode-client-secret
#          provider:
#            isxcode:
#              authorization-uri: http://localhost:8888/oauth2/v1/authorize
#              token-uri: http://localhost:8888/oauth2/v1/token
#              user-info-uri: http://localhost:8888/oauth2/v1/userinfo
#              user-name-attribute: sub
#              jwk-set-uri: http://localhost:8888/oauth2/v1/keys

server:
  servlet:
    context-path: /isxcode # 上下文

# 配置文件加密
jasypt:
  encryptor:
    property:
      prefix: "ENC@[" # 标识前缀
      suffix: "]" # 标识后缀
    bean: customJasyptStringEncryptor

isxcode:
  code: # 配置代码自动生成器
    module-path: com.isxcode.ispring.demo
    file-paths:
      'controller': controller
      'service': service
      'dao': dao
      'entity': model.entity
    templates-path: templates
    template-suffix: .ftl
    author: ispong
    ignore-fields:
      - uuid
      - version
      - created_date
      - created_by
      - last_modified_date
      - last_modified_by
    base-class-list:
      'controller': com.isxcode.ispring.common.BaseController
      'service': com.isxcode.ispring.common.BaseService
      'dao': com.isxcode.ispring.common.BaseDao
      'entity': com.isxcode.ispring.common.BaseEntity