spring:
  # profile
  profiles:
    active: dev # java -jar app.jar --spring.profiles.active=dev
  application:
    name: ispong-oxygen
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # 请求管理
  servlet:
    multipart:
      max-file-size: 3MB # 上传最大文件大小
      max-request-size: 3MB # 上传最大请求体大小

  # spring-mail
  mail:
    host: smtp.qq.com # 邮箱服务器地址
    port: 465 # 邮箱服务器端口号
    username: ENC@[4FmaVNBbiNyVZEF2cDBwGml4ufMnYB6wEMHrBTDPg8MdYWUPlgV0uRyqwfttlaIOA6jl8DpSABXJO7QBVBbkWQ==] # 邮箱账号
    password: ENC@[bc4ClJDP6nX+XWTtZkBbXPCBlOvTqaWIVogQebWagYJCAO1WBZE2qkTstMp859nCrumGTxboQpNhywo75hPIFQ==] # 邮箱密码
    default-encoding: UTF-8 # 邮件字符集
    protocol: smtp # 邮件发送协议
    test-connection: false # 是否进行连接测试
    properties:
      mail.smtp.ssl.enable: true # 启动ssl协议访问
      mail.smtp.connectiontimeout: 10000 # 设置连接超时
      mail.smtp.timeout: 10000 # 设置超时
      mail.smtp.writetimeout: 10000 # 设置写入超时

  # 数据库配置
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/h2
    username: root
    password: root
#    schema: db/schema.sql
#    data: db/data.sql

  # freemarker 设置
  freemarker:
    enabled: false # 使用启动springMvc
    cache: false # 关闭缓存
    charset: UTF-8 # 设置字符集
    template-loader-path: /templates/ # 设置模板地址
    check-template-location: false # 检查模板地址是否存在

  # h2-config
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true

# 服务器配置
server:
  servlet:
    context-path: /spring-oxygen # context
  port: 8888

# spring-logging
logging:
  level:
    root: info
    com.isxcode.oxygen.wechatgo: debug
    com.ispong.oxygen.flysql: debug
  file:
    name: ./logs/spring.log
    max-size: 10MB
    max-history: 30
    total-size-cap: 100MB
    clean-history-on-start: true
  exception-conversion-word: '%wEx'
  pattern:
    level: '%5p'
    dateformat: 'yyyy-MM-dd HH:mm:ss.SSS'
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN}}){faint} %clr(${LOG_LEVEL_PATTERN}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD}'
    file: '%d{${LOG_DATEFORMAT_PATTERN}} ${LOG_LEVEL_PATTERN} %-5(${PID:- }) --- [%15.15t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD}}'
    rolling-file-name: '${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz'

# spring-oxygen
oxygen:
  wechatgo:
    app-id: wx5ada926e5489824f # appId
    app-secret: d49e9eaac5633e661ff207353a9c86b1 # appSecret
    token: test # custom server token
  flysql:
    datasource:
      pluto:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql.definesys.com:30002/pluto_dev
        username: pluto
        password: welcome1
  system:
    file:
      location: D://

# jasypt
jasypt:
  encryptor:
    property:
      prefix: "ENC@[" # 标识前缀
      suffix: "]" # 标识后缀
    bean: customJasyptStringEncryptor # 使用自定义加密规则

# spring-actuator
management:
  endpoints:
    web:
      exposure:
        include: logfile,health,beans,metrics
  endpoint:
    logfile:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true
