server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: logfile,health,beans
  endpoint:
    logfile:
      enabled: true
    health:
      show-details: always

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.definesys.com:30002/pluto_dev
    username: pluto
    password: welcome1
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.105.33.160:3306/aicallsystem
#    username: root
#    password: ENC@[R3ZE710H1U0nsxSr1x8vJKjD2rl83XEugZwVLOBkLIbrJekh0OE+7Vpsi2lvtpLP] #liu123456.
  servlet:
    multipart:
      max-file-size: 3MB # 上传最大文件大小
      max-request-size: 3MB # 上传最大请求体大小

  # freemarker配置
  freemarker:
    template-loader-path: classpath:/templates/

# 自定义属性配置
isxcode:
  security:
    jwt-security-key: isxcode
  jwt-secret: isxcode

