spring:
  profiles:
    active: dev # java -jar app.jar --spring.profiles.active=dev
  application:
    name: ispong-oxygen
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # spring-mail 配置
  mail:
    host: smtp.qq.com # 邮箱服务器地址
    port: 465 # 邮箱服务器端口号
    username: ENC@[4FmaVNBbiNyVZEF2cDBwGml4ufMnYB6wEMHrBTDPg8MdYWUPlgV0uRyqwfttlaIOA6jl8DpSABXJO7QBVBbkWQ==] # 邮箱账号
    password: ENC@[bc4ClJDP6nX+XWTtZkBbXPCBlOvTqaWIVogQebWagYJCAO1WBZE2qkTstMp859nCrumGTxboQpNhywo75hPIFQ==] # 邮箱密码
    default-encoding: UTF-8 # 邮件字符集
    protocol: smtp # 邮件发送协议
    test-connection: false # 是否进行连接测试
    properties:
      mail.smtp.ssl.enable: true # 启动ssl协议访问
      mail.smtp.connectiontimeout: 10000 # 设置连接超时
      mail.smtp.timeout: 10000 # 设置超时
      mail.smtp.writetimeout: 10000 # 设置写入超时

# freemarker 设置
  freemarker:
    enabled: false # 使用启动springMvc
    cache: false # 关闭缓存
    charset: UTF-8 # 设置字符集
    template-loader-path: /templates/ # 设置模板地址
    check-template-location: false # 检查模板地址是否存在

server:
  servlet:
    context-path: /isxcode # 上下文

# 配置文件加密
jasypt:
  encryptor:
    property:
      prefix: "ENC@[" # 标识前缀
      suffix: "]" # 标识后缀
    bean: customJasyptStringEncryptor

isxcode:
  auto-code: # 配置代码自动生成器
    module-path: com.isxcode.ispring
    file-paths:
      'controller': controller
      'service': service
      'dao': dao
      'entity': model.entity
    templates-path: templates
    template-suffix: .ftl
    author: ispong
    ignore-fields:
      - uuid
      - version
      - created_date
      - created_by
      - last_modified_date
      - last_modified_by
    base-class-list:
      'controller': com.isxcode.ispring.common.BaseController
      'entity': com.isxcode.ispring.common.BaseEntity

logging:
  level:
    root: info
    com.isxcode.oxygen.wechatgo: debug
  file:
    name: ./logs/spring.log
    max-size: 10MB
    max-history: 30
    total-size-cap: 100MB
    clean-history-on-start: true
  exception-conversion-word: '%wEx'
  pattern:
    level: '%5p'
    dateformat: 'yyyy-MM-dd HH:mm:ss.SSS'
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN}}){faint} %clr(${LOG_LEVEL_PATTERN}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD}'
    file: '%d{${LOG_DATEFORMAT_PATTERN}} ${LOG_LEVEL_PATTERN} %-5(${PID:- }) --- [%15.15t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD}}'
    rolling-file-name: '${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz'

oxygen:
  wechatgo:
    app-id: wx5ada926e5489824f # appId
    app-secret: d49e9eaac5633e661ff207353a9c86b1 # appSecret
    token: test # custom server token