# spring-oxygen
oxygen:
  freecode:
    module-path: com.ispong.oxygen.scheduler # 模块包的位置
    author: ispong # 作者
    version: 0.0.1 # 版本号
    base-entity-class: com.ispong.oxygen.flysql.common.BaseEntity # Entity基础类
    base-controller-class: com.ispong.oxygen.flysql.common.BaseController # Controller基础类
    ignore-columns: # 忽略字段
      - uuid
      - version
      - created_date
      - created_by
      - last_modified_date
      - last_modified_by
    file-types: # 需要生成哪些文件
      - controller
      - entity
      - service
      - repository
  wechatgo:
    app-id: wx5ada926e5489824f # appId
    app-secret: d49e9eaac5633e661ff207353a9c86b1 # appSecret
    token: test # custom server token
  flysql:
    datasource:
      pluto: # 第二数据源
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql.definesys.com:30002/pluto_dev
        username: pluto
        password: welcome1
  system:
    file:
      location: D://
    quartz:
      datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:~/h2
        username: root
        password: root


